[package]
name = "sed_device"
version = "0.1.0"
edition = "2024"

[features]
test-utils = []

[dependencies]
sorbit.workspace = true
thiserror.workspace = true
num_enum.workspace = true
windows = { workspace = true, features = [
    "Win32_System_IO",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_Storage_IscsiDisc",
    "Win32_System_Ioctl",
    "Win32_Devices_DeviceAndDriverInstallation",
] }
nix.workspace = true
async-trait.workspace = true

[dev-dependencies]
sed_device = { path = ".", features = ["test-utils"] }
tokio = { workspace = true,  features = ["macros"] }
