import { Logo } from "resources/logo.slint";
import { Device, Outcome } from "data/lib.slint";
import { TabWidget } from "std-widgets.slint";
import {
    DeviceView,
    DeviceSideBar,
    DeviceSwitchView,
    DeviceScanButton,
} from "views/lib.slint";
import { TestData } from "data/lib.slint";
import {
    ToastQueue,
    ToastArea,
    ToastLevel,
} from "widgets/lib.slint";

export { ToastQueue } from "widgets/lib.slint";

export component MainWindow inherits Window {
    title: "SED Manager";
    icon: Logo.png;
    preferred-width: 1154px;
    preferred-height: 720px;

    in property <[Device]> devices: TestData.devices;
    in property <Outcome> scan-outcome;

    callback scan <=> scan-button.clicked;
    callback close-device <=> side-bar.close;
    callback take-owneship <=> device-switch-view.take-owneship;
    callback activate-locking <=> device-switch-view.activate-locking;
    callback change-password <=> device-switch-view.change-password;
    callback revert-device <=> device-switch-view.revert-device;
    callback query-stack-status <=> device-switch-view.query-stack-status;
    callback reset-stack <=> device-switch-view.reset-stack;

    HorizontalLayout {
        padding: 1.0rem;
        spacing: 1.6rem;

        side-bar := DeviceSideBar {
            devices: devices;
            max-width: 22rem;
            horizontal-stretch: 0.2;
        }

        device-switch-view := DeviceSwitchView {
            selected: side-bar.selected;
            devices: devices;
            horizontal-stretch: 1.0;
        }
    }

    scan-button := DeviceScanButton {
        x: side-bar.x;
        y: side-bar.y + side-bar.height - self.height;
        z: 1;
        outcome: scan-outcome;
    }

    ToastArea {
        x: 1rem;
        y: 1rem;
        z: 2;
        width: 20rem;
        height: parent.height - 2 * self.y;
    }
}
