//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export enum Activity { 
    description,
    take-ownership,
    activate-locking,
    change-password,
    range-editor,
    user-editor,
    access-control-editor,
    shadow-mbr,
    revert,
    com-id-status,
    stack-reset,
}

export struct ActivitySupport {
    take-ownership: bool,
    activate-locking: bool,
    change-password: bool,
    range-editor: bool,
    user-editor: bool,
    access-control-editor: bool,
    shadow-mbr: bool,
    revert: bool,
    com-id-status: bool,
    stack-reset: bool,
}
