//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export struct LockingRange {
    start-lba: int,
    end-lba: int,
    read-lock-enabled: bool,
    write-lock-enabled: bool,
    read-locked: bool,
    write-locked: bool,
}
