//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum Theme {
    system, // The first is always the default.
    dark,
    light,
}