//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export global Types {
    callback str-to-int(s: string) -> int;
    // Override this from Rust to get the full 32 bit precision.
    str-to-int(s) => {
        s.to-float()
    }
}
