import { ScrollView, Palette, GroupBox } from "std-widgets.slint";
import { IconButton, TextPlacement } from "../widgets/icon_button.slint";
import { Icons, Colors } from "../resources/lib.slint";
import { PaletteExtra } from "../widgets/lib.slint";

export enum DeviceActivity {
    capabilities,
    take-ownership,
    activate-locking,
    change-password,
    configure-locking,
    revert-device,
    stack-status,
    stack-reset,
}


export component DeviceActivityBar {
    property <length> button-height: 2.8rem;

    out property <DeviceActivity> selected-activity: capabilities;

    callback reset-stack();

    ScrollView {
        horizontal-scrollbar-policy: always-off;
        min-width: viewport.min-width;
        min-height: 8rem;

        viewport := VerticalLayout {
            spacing: 0.4rem;
            alignment: start;

            IconButton {
                text: "Capabilities";
                icon: Icons.info;
                preferred-height: button-height;
                icon-color: PaletteExtra.info-foreground;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.capabilities;
                clicked => {
                    selected-activity = DeviceActivity.capabilities;
                }
            }

            Rectangle {
                height: 0.2rem;
            }

            IconButton {
                text: "Take ownership";
                icon: Icons.take-ownership;
                preferred-height: button-height;
                icon-color: Colors.take-ownership;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.take-ownership;
                clicked => {
                    selected-activity = DeviceActivity.take-ownership;
                }
            }

            IconButton {
                text: "Activate locking";
                icon: Icons.activate-locking;
                preferred-height: button-height;
                icon-color: Colors.activate-locking;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.activate-locking;
                clicked => {
                    selected-activity = DeviceActivity.activate-locking;
                }
            }

            IconButton {
                text: "Change password";
                icon: Icons.change-password;
                preferred-height: button-height;
                icon-color: Colors.change-password;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.change-password;
                clicked => {
                    selected-activity = DeviceActivity.change-password;
                }
            }

            IconButton {
                text: "Configure locking";
                icon: Icons.configure-locking;
                preferred-height: button-height;
                icon-color: Colors.configure-locking;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.configure-locking;
                clicked => {
                    selected-activity = DeviceActivity.configure-locking;
                }
            }

            Rectangle {
                height: 0.2rem;
            }

            IconButton {
                text: "Revert device";
                icon: Icons.revert-device;
                preferred-height: button-height;
                icon-color: Colors.revert-device;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.revert-device;
                clicked => {
                    selected-activity = DeviceActivity.revert-device;
                }
            }

            Rectangle {
                height: 0.2rem;
            }

            IconButton {
                text: "Stack status";
                icon: Icons.com-id-status;
                preferred-height: button-height;
                icon-color: Colors.query-status;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: selected-activity == DeviceActivity.stack-status;
                clicked => {
                    selected-activity = DeviceActivity.stack-status;
                }
            }

            IconButton {
                text: "Reset stack";
                icon: Icons.stack-reset;
                preferred-height: button-height;
                icon-color: Colors.stack-reset;
                text-placement: TextPlacement.right;
                has-background: true;
                has-idle-background: false;
                is-selected: false; // One-click action, nothing to display.
                clicked => {
                    reset-stack()
                }
            }
        }
    }
}
