import { Device } from "../data/device.slint";
import { DeviceView } from "device_view.slint";

export component DeviceSwitchView {
    in property <int> selected;
    in property <[Device]> devices;

    callback take-owneship(device: string);
    callback activate-locking(device: string);
    callback change-password(device: string);
    callback revert-device(device: string);
    callback query-stack-status(device: string);
    callback reset-stack(device: string);

    VerticalLayout {
        if devices.length == 0: Rectangle { }

        for device[index] in devices: Rectangle {
            min-width: content.min-width;
            min-height: index == selected ? content.min-height : 0px;
            preferred-width: content.preferred-width;
            preferred-height: index == selected ? content.preferred-height : 0px;
            visible: index == selected;
            vertical-stretch: index == selected ? 1.0 : 0.0;
            content := DeviceView {
                width: parent.width;
                height: index == selected ? parent.height : self.min-height;
                device: device;

                take-owneship() => {
                    take-owneship(device.identity.path)
                };
                activate-locking() => {
                    activate-locking(device.identity.path)
                };
                change-password() => {
                    change-password(device.identity.path)
                };
                revert-device() => {
                    revert-device(device.identity.path)
                };
                query-stack-status() => {
                    query-stack-status(device.identity.path)
                };
                reset-stack() => {
                    reset-stack(device.identity.path)
                };
            }
        }
    }
}
