import { Device, Outcome } from "../data/lib.slint";
import {
    Island,
    PaletteExtra,
    VerticalSeparator,
    IconButton,
    ToastCard,
    ToastLevel,
    ToastQueue,
} from "../widgets/lib.slint";
import { Spinner, Palette, TextEdit } from "std-widgets.slint";
import { Icons } from "../resources/lib.slint";
import { HorizontalSeparator } from "../widgets/separator.slint";
import { DeviceDiscoveryView } from "device_discovery_view.slint";
import { DeviceActivityBar } from "device_activity_bar.slint";

component NameAndSerial {
    in property <Device> device;

    HorizontalLayout {
        spacing: 0.6rem;
        alignment: start;

        Text {
            text: !device.name.is-empty ? device.name : device.path;
            font-weight: 800;
            font-size: 2rem;
            color: PaletteExtra.accented-foreground;
            overflow: elide;
            vertical-alignment: center;
        }

        if !device.serial.is-empty: VerticalSeparator {
            background: @linear-gradient(0deg, #00000000 0%, PaletteExtra.separator 20%, PaletteExtra.separator 80%, #00000000 100%);
        }

        if !device.serial.is-empty: Text {
            text: !device.serial.is-empty ? device.serial : "---";
            font-size: 1.4rem;
            overflow: elide;
            vertical-alignment: center;
        }
    }
}

component Properties {
    in property <Device> device;

    // This is only so that the text can be copied easily.
    path-buffer := TextInput {
        text: device.path;
        visible: false;
    }

    HorizontalLayout {
        alignment: start;

        GridLayout {
            padding: 0.25rem;
            spacing-horizontal: 1rem;

            Text {
                row: 0;
                col: 0;
                text: "Path:";
            }

            TouchArea {
                HorizontalLayout {
                    spacing: 0.4rem;
                    alignment: start;

                    Text {
                        text: device.path;
                        overflow: elide;
                    }

                    Image {
                        source: Icons.content-copy;
                        height: 1.2rem;
                        width: 1.2rem;
                    }
                }

                double-clicked => {
                    path-buffer.copy();
                    ToastQueue.push({ title: "Path copied to clipboard", level: ToastLevel.info })
                }
            }

            Text {
                row: 1;
                col: 0;

                text: "Interface:";
                overflow: elide;
            }

            Text {
                text: device.interface;
                overflow: elide;
            }

            Text {
                row: 2;
                col: 0;

                text: "Firmware:";
                overflow: elide;
            }

            Text {
                text: device.firmware;
                overflow: elide;
            }

            Text {
                row: 3;
                col: 0;

                text: "Security commands:";
                overflow: elide;
            }

            Text {
                text: device.security_commands ? "Yes" : "No";
                overflow: elide;
            }
        }
    }
}

component Header inherits Island {
    in property <Device> device;

    HorizontalLayout {
        spacing: 0.6rem;
        padding: 0.6rem;

        Image {
            source: Icons.hard-drive;
            image-fit: ImageFit.contain;
            vertical-alignment: center;
            colorize: PaletteExtra.accented-foreground;
            width: 4rem;
        }

        VerticalLayout {
            spacing: 0.4rem;
            alignment: start;

            name-serial-block := NameAndSerial {
                device: device;
            }

            if device.status.outcome == Outcome.success: Properties {
                device: device;
            }

            if device.status.outcome == Outcome.error: ToastCard {
                notification: {
                    level: ToastLevel.error,
                    title: "Could not open device",
                    message: device.status.message,
                };
                has-icon: true;
            }

            if device.status.outcome == Outcome.pending: HorizontalLayout {
                alignment: start;
                Spinner {
                    indeterminate: true;
                    preferred-height: 4rem;
                }
            }
        }
    }
}

export component DeviceView {
    in property <Device> device;

    VerticalLayout {
        spacing: 1.6rem;

        header := Header {
            device: device;
        }

        if device.discovery.status.outcome == Outcome.success: HorizontalLayout {
            spacing: 1.6rem;
            vertical-stretch: 1.0;

            DeviceActivityBar {
                horizontal-stretch: 0.0;
            }

            DeviceDiscoveryView {
                discovery: device.discovery;
                horizontal-stretch: 1.0;
            }
        }

        if device.discovery.status.outcome == Outcome.pending: VerticalLayout {
            alignment: center;
            vertical-stretch: 1.0;
            spacing: 0.6rem;

            HorizontalLayout {
                alignment: center;
                Spinner {
                    width: 8rem;
                    height: 8rem;
                    indeterminate: true;
                }
            }

            Text {
                text: "Getting capabilities...";
                font-size: 1.4rem;
                horizontal-alignment: center;
            }
        }

        if device.discovery.status.outcome == Outcome.idle: VerticalLayout {
            alignment: center;
            vertical-stretch: 1.0;

            HorizontalLayout {
                alignment: center;

                Image {
                    width: 8rem;
                    height: 8rem;
                    source: Icons.question-mark;
                    colorize: PaletteExtra.accented-control-foreground;
                    opacity: 20%;
                }
            }
        }

        if device.discovery.status.outcome == Outcome.error: VerticalLayout {
            alignment: center;
            vertical-stretch: 1.0;

            HorizontalLayout {
                alignment: center;

                ToastCard {
                    notification: {
                        title: "Could not get capabilities",
                        message: device.discovery.status.message,
                        level: ToastLevel.error
                    };
                    has-icon: true;
                }
            }
        }
    }
}
