//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export { DeviceView } from "device_view.slint";
export { DeviceSideBar } from "device_side_bar.slint";
export { DeviceSwitchView } from "device_switch_view.slint";
export { DeviceScanButton } from "device_scan_button.slint";
