import { LineEdit } from "std-widgets.slint";

export component PasswordForm {
    in property <string> new-password-label: "New password:";
    in property <string> repeat-password-label: "Repeat password:";
    out property <bool> matches: password.text == repeat-password.text;

    VerticalLayout {
        spacing: 0.5rem;

        Text {
            text: new-password-label;
        }

        password := LineEdit {
            input-type: InputType.password;
        }

        Text {
            text: repeat-password-label;
        }

        repeat-password := LineEdit {
            input-type: InputType.password;
        }
    }
}
