export global PasswordValidator {
    public pure function validate(password: string, repeat: string) -> string {
        if password == "123" || password == "password" || password == "asd" {
            "Really?"
        } else if password == "1234" {
            "Cannot be the same as mine"
        } else if password != repeat {
            "Passwords do not match"
        } else {
            "";
        }
    }
}
