import { Palette } from "std-widgets.slint";


export global PaletteExtra {
    out property <color> separator: Palette.foreground.mix(Palette.background, 0.27);
    out property <color> error-foreground: Palette.foreground.mix(#FF0000, 0.3);
    out property <color> warning-foreground: Palette.foreground.mix(#FFD000, 0.3);
    out property <color> action-foreground: Palette.foreground.mix(Palette.accent-background, 0.4);
}

export component HorizontalSeparator inherits Rectangle {
    width: 100%;
    height: 1px;
    background: PaletteExtra.separator;
}

export component VerticalSeparator inherits Rectangle {
    width: 1px;
    height: 100%;
    background: PaletteExtra.separator;
}

export component Island inherits Rectangle {
    background: Palette.control-background;
    border-radius: 8px;

    // Get padding from sides that give `distance` at the rounded corners.
    public pure function corner-padding(distance: length) -> length {
        (self.border-radius * (Math.sqrt(2.0) - 1.0) + distance) / Math.sqrt(2.0);
    }
}
