export global Icons {
    out property <image> none: @image-url("");

    // General
    out property <image> sed-manager: @image-url("../images/logo.png");
    out property <image> refresh: @image-url("../images/action/8666728_refresh_cw_icon.svg");
    out property <image> hard-drive: @image-url("../images/device/8666570_hard_drive_icon.svg");
    out property <image> hard-drive-pretty: @image-url("../images/device/3671772_ATTRIB_drive_hard_icon.svg");
    out property <image> no-encryption: @image-url("../images/device/9111167_lock_no_icon.svg");

    // Activity types
    out property <image> settings: @image-url("../images/action/8666615_settings_icon.svg");
    out property <image> troubleshoot: @image-url("../images/action/construction_24dp_E3E3E3.svg");
    out property <image> table-editor: @image-url("../images/action/9111030_table_icon.svg");
    // Configure activities
    out property <image> take-ownership: @image-url("../images/action/home_24dp.svg");
    out property <image> activate-locking: @image-url("../images/device/9111193_lock_icon.svg");
    out property <image> locking-ranges: @image-url("../images/action/segment_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> users: @image-url("../images/action/person_edit_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> permissions: @image-url("../images/action/passkey_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> mbr-shadowing: @image-url("../images/action/tonality_24dp.svg");
    out property <image> revert: @image-url("../images/action/lock_reset_24dp.svg");
    // Troubleshoot activities
    out property <image> com-id-status: @image-url("../images/action/monitor_heart_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> stack-reset: @image-url("../images/action/reset_wrench_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    // Table editor activities
    out property <image> security-provider: @image-url("../images/device/9111101_key_security_icon.svg");

    // Shapes
    out property <image> arrow-left: @image-url("../images/shape/8666600_arrow_left_icon.svg");
    out property <image> chevron-arrow-up: @image-url("../images/shape/8666673_chevron_up_icon.svg");
    out property <image> chevron-arrow-down: @image-url("../images/shape/8666558_chevron_down_icon.svg");
    out property <image> chevron-arrow-right: @image-url("../images/shape/8666777_chevron_right_arrow_icon.svg");

    // Actions
    out property <image> delete-forever: @image-url("../images/action/delete_forever.svg");
    out property <image> error: @image-url("../images/error/8666566_alert_circle_icon.svg");
    out property <image> warning: @image-url("../images/error/8666599_alert_triangle_icon.svg");
    out property <image> password: @image-url("../images/action/password_2_24dp.svg");
    out property <image> upload: @image-url("../images/action/upload_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> file-open: @image-url("../images/action/file_open_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
    out property <image> close: @image-url("../images/action/close_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg");
}
