//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export global Icons {
    out property <image> none: @image-url("");

    // General
    out property <image> sed-manager: @image-url("../images/logo.png");
    out property <image> refresh: @image-url("../images/action/refresh.svg");
    out property <image> hard-drive: @image-url("../images/device/hard_drive.svg");
    out property <image> no-encryption: @image-url("../images/device/no_encryption.svg");

    // Activity types
    out property <image> settings: @image-url("../images/action/settings.svg");
    out property <image> troubleshoot: @image-url("../images/action/troubleshoot.svg");
    // Configure activities
    out property <image> take-ownership: @image-url("../images/action/rocket_launch.svg");
    out property <image> activate-locking: @image-url("../images/device/lock.svg");
    out property <image> locking-ranges: @image-url("../images/device/segment.svg");
    out property <image> users: @image-url("../images/action/person_edit.svg");
    out property <image> permissions: @image-url("../images/action/passkey.svg");
    out property <image> mbr-shadowing: @image-url("../images/action/tonality.svg");
    out property <image> revert: @image-url("../images/action/lock_reset.svg");
    // Troubleshoot activities
    out property <image> com-id-status: @image-url("../images/action/query_stats.svg");
    out property <image> stack-reset: @image-url("../images/action/reset_wrench.svg");

    // Shapes
    out property <image> arrow-left: @image-url("../images/shape/arrow_back_ios.svg");
    out property <image> chevron-arrow-up: @image-url("../images/shape/chevron_up.svg");
    out property <image> chevron-arrow-down: @image-url("../images/shape/chevron_down.svg");
    out property <image> chevron-arrow-right: @image-url("../images/shape/chevron_right.svg");

    // Actions
    out property <image> delete-forever: @image-url("../images/action/ink_eraser.svg");
    out property <image> error: @image-url("../images/error/error.svg");
    out property <image> warning: @image-url("../images/error/warning.svg");
    out property <image> password: @image-url("../images/action/pin.svg");
    out property <image> upload: @image-url("../images/action/upload_file.svg");
    out property <image> file-open: @image-url("../images/action/file_open.svg");
    out property <image> close: @image-url("../images/action/close.svg");
    out property <image> cancel: @image-url("../images/action/cancel.svg");
}
