name: "Feature request"
description: "Suggest an idea for this project"
labels: ["feature-request"]
body:
  - type: textarea
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: A clear and concise description of what the problem is.
      placeholder: |
        I have multiple encrypted drives, but the PBA unlocks only the one with the shadow MBR.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the feature or solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        I would like the PBA to unlock all of my drives when entering the password on bootup.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        I've tried firing up SEDManager after bootup and manually unlocking the drives, but it's rather cumbersome. Maybe I could automate this by configring an autorun in the operating system if SEDManager had a CLI that can unlock the drives.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information, context, screenshots or log files you have.
    validations:
      required: false