import { GroupBox, Button, Palette, ScrollView } from "std-widgets.slint";
import { CollapsibleView } from "../../widgets/collapsible_view.slint";
import { NavigationButton, NavigationDirection } from "../../widgets/navigation_button.slint";
import { HorizontalSeparator, PaletteExtra } from "../../widgets/visual.slint";

export component ActionView {
    in property <[string]> security-providers;
    private property <length> button-height: 32px;
    callback take-ownership();
    callback activate-locking();
    callback configure-ranges();
    callback revert();
    callback update-com-id-status();
    callback stack-reset();
    ScrollView {
        horizontal-scrollbar-policy: always-off;
        min-width: viewport.min-width;
        min-height: 128px;
        viewport := VerticalLayout {
            alignment: start;
            spacing: 12px;
            CollapsibleView {
                text: "Configure";
                icon: @image-url("../../../images/action/8666615_settings_icon.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Take ownership";
                        icon: @image-url("../../../images/action/8666628_user_check_icon.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        clicked => {
                            take-ownership();
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Activate locking";
                        icon: @image-url("../../../images/device/9111193_lock_icon.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        clicked => {
                            activate-locking();
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Configure ranges";
                        icon: @image-url("../../../images/action/menu.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        clicked => {
                            configure-ranges();
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Revert";
                        icon: @image-url("../../../images/action/user-x.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        clicked => {
                            revert();
                        }
                    }
                }
            }

            CollapsibleView {
                text: "Troubleshoot";
                icon: @image-url("../../../images/action/construction_24dp_E3E3E3.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "ComID status";
                        icon: @image-url("../../../images/action/activity.svg");
                        height: button-height;
                        background: #00000000;
                        clicked => {
                            update-com-id-status()
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Stack reset";
                        icon: @image-url("../../../images/action/restart_alt_24dp_E3E3E3.svg");
                        height: button-height;
                        background: #00000000;
                        clicked => {
                            stack-reset()
                        }
                    }
                }
            }

            if root.security-providers.length > 0: CollapsibleView {
                text: "Table editor";
                icon: @image-url("../../../images/action/9111030_table_icon.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    for sp in security_providers: VerticalLayout {
                        alignment: start;
                        HorizontalSeparator {
                            background: Palette.background;
                        }

                        NavigationButton {
                            text: sp + " SP";
                            icon: @image-url("../../../images/device/9111101_key_security_icon.svg");
                            height: button-height;
                            navigation-direction: NavigationDirection.left;
                            background: #00000000;
                            enabled: false;
                        }
                    }
                }
            }
        }
    }
}

export component LivePreviewTest inherits ActionView {
    security-providers: ["Admin", "Locking"];
}
