import { ScrollView, GridBox, HorizontalBox, Palette } from "std-widgets.slint";
import { VerticalSeparator, PaletteExtra } from "../widgets/visual.slint";
import { CollapsibleView } from "../widgets/collapsible_view.slint";
import { NameValueListView } from "../widgets/name_value_list_view.slint";
import { ContentStatus, TextLoadingIndicator } from "../widgets/loading.slint";

export struct FeatureModel {
    name: string,
    nvps: [{name: string, value: string}],    
}

component LoadingView {
    property <length> spacing: 16px;
    min-width: 16px + 2 * Math.max(common-view.min-width, ssc-view.min-width);
    min-height: Math.max(common-view.min-height, ssc-view.min-height);
    common-view := CollapsibleView {
        x: 0;
        y: 0;
        width: (root.width - root.spacing) / 2;
        title: "Common features";
        height: self.min-height;
        VerticalLayout {
            padding: 6px;
            alignment: start;
            TextLoadingIndicator {
                min-width: 60px;
                height: 16px;
            }
        }
    }

    ssc-view := CollapsibleView {
        x: common-view.width + root.spacing;
        y: 0;
        width: common-view.width;
        title: "SSC features";
        height: self.min-height;
        VerticalLayout {
            padding: 6px;
            alignment: start;
            TextLoadingIndicator {
                min-width: 60px;
                height: 16px;
            }
        }
    }
}

component ErrorView {
    in property <string> error;
    VerticalLayout {
        alignment: center;
        padding: 12px;
        spacing: 8px;
        Image {
            source: @image-url("../../logo/icon_no_lock.svg");
            preferred-height: 200px;
            min-height: 80px;
            colorize: PaletteExtra.action-foreground.with-alpha(0.6);
        }

        Text {
            text: "No encryption features found";
            font-size: 14px;
            horizontal-alignment: center;
        }

        Text {
            text: root.error;
            font-size: 14px;
            horizontal-alignment: center;
        }
    }
}

component SplitView {
    in property <[FeatureModel]> common-features;
    in property <[FeatureModel]> ssc-features;
    HorizontalLayout {
        alignment: stretch;
        spacing: 16px;
        preferred-width: 100%;
        if root.common-features.length != 0: ScrollView {
            horizontal-scrollbar-policy: always-off;
            min-width: common_feature_view.min-width;
            viewport-height: common_feature_view.min-height;
            common_feature_view := VerticalLayout {
                preferred-width: 100%;
                spacing: 16px;
                for feature in root.common-features: CollapsibleView {
                    title: feature.name;
                    NameValueListView {
                        name_value_pairs: feature.nvps;
                    }
                }
            }
        }
        if root.ssc-features.length != 0: ScrollView {
            horizontal-scrollbar-policy: always-off;
            min-width: ssc_feature_view.min-width;
            viewport-height: ssc_feature_view.min-height;
            ssc_feature_view := VerticalLayout {
                preferred-width: 100%;
                spacing: 16px;
                for feature in root.ssc-features: CollapsibleView {
                    title: feature.name;
                    NameValueListView {
                        name_value_pairs: feature.nvps;
                    }
                }
            }
        }
    }
}

export component FeatureView {
    in property <ContentStatus> status: ContentStatus.loading;
    in property <string> error;
    in property <[FeatureModel]> common-features;
    in property <[FeatureModel]> ssc-features;
    HorizontalLayout {
        if root.status == ContentStatus.loading: LoadingView { }
        if root.status == ContentStatus.error: ErrorView {
            error: root.error;
        }
        if root.status == ContentStatus.success: SplitView {
            preferred-width: 100%;
            preferred-height: 100%;
            common-features: root.common-features;
            ssc-features: root.ssc-features;
        }
    }
}

export component LivePreviewTest_Filled inherits FeatureView {
    common-features: [
        {
            name: "TPer",
            nvps: [{ name: "Sync supported", value: "Yes" }, { name: "Async supported", value: "No" }],
        },
        {
            name: "Locking",
            nvps: [
                { name: "Locked", value: "No" },
            ],
        }
    ];
    ssc-features: [
        {
            name: "Opal 2.0",
            nvps: [{ name: "Num admins supported", value: "4" }],
        },
    ];
}
