import { Island, PaletteExtra } from "../widgets/visual.slint";
import { ContentStatus } from "../data/content_status.slint";
import { Button, Palette, Spinner } from "std-widgets.slint";
import { ActionResult} from "../data/action_result.slint";
import { SolidPopupWindow } from "../widgets/solid_popup_window.slint";
import { ConfigView } from "config_view.slint";

component StatusIndicator {
    in property <ContentStatus> status;
    in property <image> action-icon;
    VerticalLayout {
        alignment: center;
        if status == ContentStatus.loading: Spinner {
            width: 80px;
            height: 80px;
            indeterminate: true;
        }
        if status == ContentStatus.error: Image {
            width: 80px;
            height: 80px;
            source: @image-url("../../images/error/8666566_alert_circle_icon.svg");
            colorize: PaletteExtra.error-foreground;
        }
        if status == ContentStatus.success: Image {
            width: 80px;
            height: 80px;
            source: action-icon;
            colorize: PaletteExtra.success-foreground;
        }
    }
}

export component StatusPopup inherits SolidPopupWindow {
    in property <ActionResult> result;
    in property <image> action-icon;
    callback back();
    changed result => {
        root.height = content.min-height;
    }
    width: 260px;
    height: content.min-height;
    content := VerticalLayout {
        padding: 12px;
        spacing: 12px;
        alignment: start;
        HorizontalLayout {
            alignment: center;
            StatusIndicator {
                status: result.status;
                action-icon: action-icon;
            }
        }

        Text {
            text: {
                if result.status == ContentStatus.loading {
                    "Please wait..."
                } else if result.status == ContentStatus.success {
                    "Success!"
                } else {
                    "Failed: " + result.error-message
                }
            }
            horizontal-alignment: center;
            color: {
                if result.status == ContentStatus.loading {
                    Palette.control-foreground
                } else if result.status == ContentStatus.success {
                    PaletteExtra.success-foreground
                } else {
                    PaletteExtra.error-foreground
                }
            }
            wrap: TextWrap.word-wrap;
        }

        HorizontalLayout {
            spacing: 6px;
            alignment: center;
            Button {
                text: "Retry";
                width: 90px;
                enabled: result.status != ContentStatus.loading;
                clicked => {
                    root.close()
                }
            }

            Button {
                text: "Back";
                width: 90px;
                enabled: result.status != ContentStatus.loading;
                clicked => {
                    root.close();
                    root.back();
                }
            }
        }
    }
}

export component OneClickConfigView inherits ConfigView {
    in property <ActionResult> result: { status: ContentStatus.error };
    back-enabled: result.status != ContentStatus.loading;
    public function start() {
        status-popup.show()
    }
    status-popup := StatusPopup {
        x: form.x + (form.width - self.width) / 2;
        y: form.y + (form.height - self.height) / 2;
        close-policy: no-auto-close;
        result: result;
        action-icon: root.config-icon;
        back => {
            root.back()
        }
    }

    form := HorizontalLayout {
        vertical-stretch: 1;
        spacing: 16px;
        preferred-height: 100%;
        alignment: center;
        VerticalLayout {
            alignment: center;
            @children
        }
    }
}

export component LivePreviewTest inherits OneClickConfigView {
    device-name: "Foo Device";
    config-name: "Take ownership";
    timer := Timer {
        interval: 2s;
        running: false;
        triggered => {
            self.running = false;
            root.result = {
                status: ContentStatus.error,
                error-message: "this is a long error message to describe what the hell happened"
            }
        }
    }

    Button {
        text: timer.running ? "Running" : "Start";
        clicked => {
            root.start();
            timer.running = true;
        }
    }
}
