import { Palette } from "std-widgets.slint";

export component SolidPopupWindow inherits PopupWindow {
    Rectangle {
        background: Palette.background;
        border-radius: 16px;
        drop-shadow-color: #00000080;
        drop-shadow-blur: 12px;
        drop-shadow-offset-x: 2px;
        drop-shadow-offset-y: 2px;
        opacity: 95%;
    }

    Rectangle {
        background: Palette.control-background;
        border-radius: 16px;
        opacity: 95%;
    }
}
