import { Status } from "status.slint";

export struct DiscoveryProperty {
    name: string,
    value: string,
}

export struct DiscoveryFeature {
    name: string,
    properties: [DiscoveryProperty],
}

export struct Discovery {
    status: Status,
    common-features: [DiscoveryFeature],
    ssc-features: [DiscoveryFeature],
}

export struct DeviceConfig {
    sid-msid-pin-differ: bool,
    locking-enabled: bool,
}

export struct Identity {
    name: string,
    serial: string,
    path: string,
    firmware: string,
    interface: string,
    security-commands: bool,
    is-removable: bool,
}

export struct ComIdStatus {
    good: bool,
    com-id: int,
    com-id-ext: int,
    status: string,
}

export struct ProtocolProperty {
    name: string,
    host: string,
    device: string,
    connection: string,
}

export struct StackStatus {
    com-id: ComIdStatus,
    protocol: [ProtocolProperty],
}

export struct Device {
    status: Status,
    identity: Identity,
    discovery: Discovery,
    config: DeviceConfig,
    stack_status: StackStatus,
}
