import { Status } from "status.slint";

export struct DiscoveryProperty {
    name: string,
    value: string,
}

export struct DiscoveryFeature {
    name: string,
    properties: [DiscoveryProperty],
}

export struct Discovery {
    status: Status,
    common-features: [DiscoveryFeature],
    ssc-features: [DiscoveryFeature],
}

export struct DiscoveryExcerpt {
    owned: bool,
    activated: bool,
}

export struct Identity {
    name: string,
    serial: string,
    path: string,
    firmware: string,
    interface: string,
    security_commands: bool,
    is_removable: bool,
}

export struct StackStatus {
    connected: bool,
    com_id: int,
    com_id_ext: int,
    com_id_status: string,
}

export struct Device {
    status: Status,
    identity: Identity,
    discovery: Discovery,
    discovery_excerpt: DiscoveryExcerpt,
    stack_status: StackStatus,
}
