//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export enum Outcome {
    success,
    error,
    pending,
    idle,
}

export struct Status {
    outcome: Outcome,
    message: string,
}
