import { Device } from "device.slint";
import { Status, Outcome } from "status.slint";

export global TestData {
    out property <[Device]> devices: [
        {
            identity: {
                name: "Storaginator 1000",
                serial: "SERIAL#3244",
                path: "/dev/nvme0",
                firmware: "FIRMWARE#4543",
                interface: "NVMe",
                security_commands: true,
                is_removable: false,
            },
            discovery: {
                status: { outcome: Outcome.success },
                common-features: [
                    {
                        name: "TPer",
                        properties: [
                            { name: "Sync supported", value: "Yes" },
                            { name: "Async supported", value: "No" },
                        ],
                    },
                    {
                        name: "Locking",
                        properties: [
                            { name: "Locked", value: "No" },
                            { name: "Encryption supported", value: "Yes" },
                        ],
                    },
                ],
                ssc-features: [
                    {
                        name: "Opal 1.0",
                        properties: [
                            { name: "Base ComID", value: "4096" },
                            { name: "Num ComIDs", value: "1" },
                            { name: "Initial SID password", value: "MSID" },
                        ],
                    },
                ],
            },
            stack-status: {
                connected: true,
                com-id: 3072,
                com-id-ext: 0,
                com-id-status: "Issued",
            }
        },
        {
            identity: {
                name: "Storaginator 2000",
                serial: "SERIAL#8255",
                path: "/dev/sda/success/very/long/device/path",
                firmware: "FIRMWARE#9912",
                interface: "SATA",
                security_commands: false,
                is_removable: true,
            },
            discovery: {
                status: { outcome: Outcome.pending },
            },
        },
        {
            identity: {
                name: "Storaginator 3000",
                serial: "SERIAL#8255",
                path: "/dev/sde",
                firmware: "FIRMWARE#3422",
                interface: "USB",
                security_commands: false,
                is_removable: true,
            },
            discovery: {
                status: { outcome: Outcome.error, message: "IF-RECV failed yadda yadda." },
            },
        },
        {
            status: {
                outcome: Outcome.error,
                message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            },
            identity: {
                name: "",
                serial: "",
                path: "/dev/sdb/error/very/long/device/path",
                firmware: "",
                interface: "",
                security_commands: false,
                is_removable: false,
            },
            discovery: {
                status: { outcome: Outcome.idle },
            },
        },
        {
            status: { outcome: Outcome.pending },
            identity: {
                name: "",
                serial: "",
                path: "/dev/sdc",
                firmware: "",
                interface: "",
                security_commands: false,
                is_removable: false,
            },
            discovery: {
                status: { outcome: Outcome.idle },
            },
        },
    ];
}
