import { SummaryModel, SummaryPage, LivePreviewData as LivePreviewSummaryData } from "summary_page.slint";
import { AdditionalDrivesPage, AdditionalDrivesModel } from "additional_drives_page.slint";
import { ScrollView, Palette, Button } from "std-widgets.slint";
import { ContentStatus } from "../widgets/loading.slint";
import { PaletteExtra } from "../widgets/visual.slint";


component Tab inherits Rectangle {
    in property <string> name;
    in property <bool> selected;
    width: 240px;
    height: 32px;
    border-radius: 6px;
    background: selected ? PaletteExtra.accented-control-background : area.has-hover ? PaletteExtra.highlight : Palette.background;
    border-width: 1px;
    border-color: selected ? self.background : PaletteExtra.highlight;
    callback clicked <=> area.clicked;
    area := TouchArea {
        width: parent.width;
        height: parent.height;
    }

    Text {
        text: name;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-weight: 600;
        color: selected ? Palette.control-foreground : Palette.foreground;
    }
}

export component MainPage inherits Window {
    in-out property <int> active-tab: 0;
    in property <[SummaryModel]> summaries;
    in property <AdditionalDrivesModel> additional-drives;
    callback update-device-list();
    callback update-device-discovery(device-idx: int);
    function on-tab-selected(tab: int) {
        self.active-tab = tab;
        if tab < self.summaries.length {
            update-device-discovery(tab);
        }
    }
    changed summaries => {
        self.on-tab-selected(Math.min(self.active-tab, summaries.length))
    }
    VerticalLayout {
        alignment: stretch;
        padding-left: 16px;
        padding-right: 16px;
        padding-bottom: 16px;
        padding-top: 6px;
        HorizontalLayout {
            ScrollView {
                vertical-scrollbar-policy: always-off;
                preferred-height: tabs.preferred-height;
                horizontal-stretch: 1.0;
                vertical-stretch: 0.0;
                tabs := HorizontalLayout {
                    spacing: 4px;
                    for summary[i] in summaries: Tab {
                        name: summary.name;
                        selected: root.active-tab == i;
                        clicked => {
                            on-tab-selected(i);
                        }
                    }
                    if additional-drives.status != ContentStatus.success || additional-drives.drives.length != 0: Tab {
                        name: "Unavailable drives";
                        selected: root.active-tab == summaries.length;
                        clicked => {
                            on-tab-selected(summaries.length);
                        }
                    }
                }
            }

            Rectangle {
                width: 0px;
                height: 32px;
                Rectangle {
                    width: 33px;
                    height: 36px;
                    x: -32px;
                    y: -2px;
                    background: @linear-gradient(90deg, Palette.background.with-alpha(0) 0%, Palette.background 80%);
                }
            }

            Button {
                height: 32px;
                icon: @image-url("../../images/action/8666728_refresh_cw_icon.svg");
                colorize-icon: true;
                clicked => {
                    update-device-list();
                }
            }
        }

        HorizontalLayout {
            max-height: 100000px; // Otherwise it assumes max-height == min-height
            vertical-stretch: 1.0;
            for summary[i] in root.summaries: HorizontalLayout {
                if i == active-tab: SummaryPage {
                    summary: summary;
                }
            }
            if root.summaries.length == active-tab: AdditionalDrivesPage {
                additional-drives: root.additional-drives;
            }
        }
    }
}

export component LivePreviewTest inherits MainPage {
    summaries: [LivePreviewSummaryData.summary, LivePreviewSummaryData.summary];
}
