[package]
name = "sed_manager_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
sed_device.workspace = true
sed_tper.workspace = true
sed_manager.workspace = true
sed_packet.workspace = true
sed_manager_gui_slint.workspace = true
sed_async_runtime.workspace = true
sed_virtual_device.workspace = true
sed_telemetry.workspace = true
slint.workspace = true
tracing.workspace = true
