import { GroupBox, Button, Palette, ScrollView } from "std-widgets.slint";
import { Collapsible } from "../../widgets/collapsible.slint";
import { NavigationButton, NavigationDirection } from "../../widgets/navigation_button.slint";
import { HorizontalSeparator, PaletteExtra } from "../../widgets/visual.slint";
import { Activity, ActivitySupport } from "../../data/activity.slint";

export component ActivityLauncher {
    in property <ActivitySupport> activity-support;
    in property <[string]> security-providers;
    private property <length> button-height: 32px;
    callback select-activity(activity: Activity);
    ScrollView {
        horizontal-scrollbar-policy: always-off;
        min-width: viewport.min-width;
        min-height: 128px;
        viewport := VerticalLayout {
            alignment: start;
            spacing: 12px;
            Collapsible {
                text: "Configure";
                icon: @image-url("../../../images/action/8666615_settings_icon.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Take ownership";
                        icon: @image-url("../../../images/action/home_24dp.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.success-foreground;
                        enabled: activity-support.take-ownership;
                        clicked => {
                            select-activity(Activity.take-ownership);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Activate locking";
                        icon: @image-url("../../../images/device/9111193_lock_icon.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#ffc400, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.activate-locking;
                        clicked => {
                            select-activity(Activity.activate-locking);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Locking ranges";
                        icon: @image-url("../../../images/shape/arrow_range_24dp.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#9900ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.locking-ranges;
                        clicked => {
                            select-activity(Activity.locking-ranges);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Users";
                        icon: @image-url("../../../images/action/users.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#006eff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.users;
                        clicked => {
                            select-activity(Activity.users);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Permissions";
                        icon: @image-url("../../../images/action/award.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.success-foreground;
                        enabled: activity-support.permissions;
                        clicked => {
                            select-activity(Activity.permissions);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "MBR Shadowing";
                        icon: @image-url("../../../images/action/tonality_24dp.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#96fcff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.shadow-mbr;
                        clicked => {
                            select-activity(Activity.shadow-mbr);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Revert";
                        icon: @image-url("../../../images/action/lock_reset_24dp.svg");
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.error-foreground;
                        enabled: activity-support.revert;
                        clicked => {
                            select-activity(Activity.revert);
                        }
                    }
                }
            }

            Collapsible {
                text: "Troubleshoot";
                icon: @image-url("../../../images/action/construction_24dp_E3E3E3.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "ComID status";
                        icon: @image-url("../../../images/action/activity.svg");
                        height: button-height;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#ff46ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.com-id-status;
                        clicked => {
                            select-activity(Activity.com-id-status);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Stack reset";
                        icon: @image-url("../../../images/action/restart_alt_24dp_E3E3E3.svg");
                        height: button-height;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#00a2ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.stack-reset;
                        clicked => {
                            select-activity(Activity.stack-reset);
                        }
                    }
                }
            }

            if root.security-providers.length > 0: Collapsible {
                text: "Table editor";
                icon: @image-url("../../../images/action/9111030_table_icon.svg");
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    for sp in security_providers: VerticalLayout {
                        alignment: start;
                        HorizontalSeparator {
                            background: Palette.background;
                        }

                        NavigationButton {
                            text: sp + " SP";
                            icon: @image-url("../../../images/device/9111101_key_security_icon.svg");
                            height: button-height;
                            navigation-direction: NavigationDirection.left;
                            background: #00000000;
                            icon-color: PaletteExtra.make-accented(#ffc400, Palette.control-foreground, Palette.control-background);
                            enabled: false;
                        }
                    }
                }
            }
        }
    }
}

export component LivePreviewTest inherits ActivityLauncher {
    security-providers: ["Admin", "Locking"];
}
