import { GroupBox, Button, Palette, ScrollView } from "std-widgets.slint";
import { Collapsible } from "../../widgets/collapsible.slint";
import { NavigationButton, NavigationDirection } from "../../widgets/navigation_button.slint";
import { HorizontalSeparator, PaletteExtra } from "../../widgets/visual.slint";
import { Activity, ActivitySupport } from "../../data/activity.slint";
import { Icons } from "../../icons.slint";

export component ActivityLauncher {
    in property <ActivitySupport> activity-support;
    in property <[string]> security-providers;
    private property <length> button-height: 32px;
    callback select-activity(activity: Activity);
    ScrollView {
        horizontal-scrollbar-policy: always-off;
        min-width: viewport.min-width;
        min-height: 128px;
        viewport := VerticalLayout {
            alignment: start;
            spacing: 12px;
            Collapsible {
                text: "Configure";
                icon: Icons.settings;
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Take ownership";
                        icon: Icons.take-ownership;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.success-foreground;
                        enabled: activity-support.take-ownership;
                        clicked => {
                            select-activity(Activity.take-ownership);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Activate locking";
                        icon: Icons.activate-locking;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#ffc400, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.activate-locking;
                        clicked => {
                            select-activity(Activity.activate-locking);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit ranges";
                        icon: Icons.locking-ranges;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#9900ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.range-editor;
                        clicked => {
                            select-activity(Activity.range-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit users";
                        icon: Icons.users;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#006eff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.user-editor;
                        clicked => {
                            select-activity(Activity.user-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit permissions";
                        icon: Icons.permissions;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.success-foreground;
                        enabled: activity-support.access-control-editor;
                        clicked => {
                            select-activity(Activity.access-control-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Shadow MBR";
                        icon: Icons.mbr-shadowing;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#96fcff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.shadow-mbr;
                        clicked => {
                            select-activity(Activity.shadow-mbr);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Revert device";
                        icon: Icons.revert;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: PaletteExtra.error-foreground;
                        enabled: activity-support.revert;
                        clicked => {
                            select-activity(Activity.revert);
                        }
                    }
                }
            }

            Collapsible {
                text: "Troubleshoot";
                icon: Icons.troubleshoot;
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Query stack status";
                        icon: Icons.com-id-status;
                        height: button-height;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#ff46ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.com-id-status;
                        clicked => {
                            select-activity(Activity.com-id-status);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Reset stack";
                        icon: Icons.stack-reset;
                        height: button-height;
                        background: #00000000;
                        icon-color: PaletteExtra.make-accented(#00a2ff, Palette.control-foreground, Palette.control-background);
                        enabled: activity-support.stack-reset;
                        clicked => {
                            select-activity(Activity.stack-reset);
                        }
                    }
                }
            }

            if false && root.security-providers.length > 0: Collapsible {
                text: "Table editor";
                icon: Icons.table-editor;
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    for sp in security_providers: VerticalLayout {
                        alignment: start;
                        HorizontalSeparator {
                            background: Palette.background;
                        }

                        NavigationButton {
                            text: sp + " SP";
                            icon: Icons.security-provider;
                            height: button-height;
                            navigation-direction: NavigationDirection.left;
                            background: #00000000;
                            icon-color: PaletteExtra.make-accented(#ffc400, Palette.control-foreground, Palette.control-background);
                            enabled: false;
                        }
                    }
                }
            }
        }
    }
}

export component LivePreviewTest inherits ActivityLauncher {
    security-providers: ["Admin", "Locking"];
}
