import { NameValuePair } from "name_value_pair.slint";
import { ExtendedStatus, Status } from "status.slint";
import { ActivitySupport } from "activity.slint";

export struct DeviceIdentity {
    name: string,
    serial: string,
    path: string,
    firmware: string,
    interface: string,
}

export struct DeviceDiscoveryFeature {
    name: string,
    properties: [NameValuePair],    
}


export struct DeviceDiscovery {
    security-subsystem-classes: [string],
    security-providers: [string],
    common-features: [DeviceDiscoveryFeature],
    ssc-features: [DeviceDiscoveryFeature],    
}

export struct DeviceGeometry {
    block-size: int,
    block-alignment: int,
    lowest-aligned-block: int,
}

export struct DeviceDescription {
    identity: DeviceIdentity,
    discovery-status: ExtendedStatus,
    discovery: DeviceDiscovery,
    activity-support: ActivitySupport,
    geometry: DeviceGeometry,
}


export global ExampleData {
    out property <DeviceDescription> description: {
        identity: {
            name: "Test Storage Device",
            serial: "0123456ABCDEF",
            path: "/dev/this/may/actually/be/a/very/long/path/on/windows/nvme0",
            firmware: "FW1.0",
            interface: "NVMe",
        },
        discovery-status: { status: Status.success },
        discovery: {
            security-subsystem-classes: ["Opal 1.0", "Opal 2.0"],
            security-providers: ["Admin", "Locking"],
            common-features: [
                {
                    name: "TPer features",
                    properties: [{ name: "Sync supported", value: "Yes" }, { name: "Async supported", value: "No" }],
                },
                {
                    name: "Locking features",
                    properties: [
                        { name: "Locked", value: "No" },
                    ],
                }
            ],
            ssc-features: [
                {
                    name: "Opal 2.0 features",
                    properties: [{ name: "Num admins supported", value: "4" }],
                },
            ],
        },
        activity-support: {
            take-ownership: true,
            activate-locking: true,
            range-editor: true,
            user-editor: true,
            access-control-editor: true,
            shadow-mbr: false,
            revert: true,
            com-id-status: true,
            stack-reset: true,
        }
    };
}
