import { PaletteExtra } from "../widgets/palette_extra.slint";
import { Palette } from "std-widgets.slint";

export global Colors {
    // Main actions
    out property <color> take-ownership: PaletteExtra.make-accented(#00da36, Palette.control-foreground, Palette.control-background);
    out property <color> activate-locking: PaletteExtra.make-accented(#50ffdf, Palette.control-foreground, Palette.control-background);
    out property <color> change-password: PaletteExtra.make-accented(#00a2ff, Palette.control-foreground, Palette.control-background);
    out property <color> configure-locking: PaletteExtra.make-accented(#8850ff, Palette.control-foreground, Palette.control-background);
    out property <color> revert-device: PaletteExtra.error-foreground;

    // Troubleshooting
    out property <color> query-status: PaletteExtra.make-accented(#10b050, Palette.control-foreground, Palette.control-background);
    out property <color> stack-reset: PaletteExtra.make-accented(#ff9020, Palette.control-foreground, Palette.control-background);

    // Configure locking options
    out property <color> edit-ranges: PaletteExtra.make-accented(#9900ff, Palette.control-foreground, Palette.control-background);
    out property <color> edit-authorities: PaletteExtra.make-accented(#006eff, Palette.control-foreground, Palette.control-background);
    out property <color> edit-permissions: PaletteExtra.make-accented(#ff9900, Palette.control-foreground, Palette.control-background);
    out property <color> shadow-mbr: PaletteExtra.make-accented(#96fcff, Palette.control-foreground, Palette.control-background);
}
