//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { PaletteExtra } from "../view/palette_extra.slint";
import { Palette } from "std-widgets.slint";

export global Icons {
    out property <image> none: @image-url("");

    // General
    out property <image> refresh: @image-url("../../resources/icons/action/refresh.svg");
    out property <image> hard-drive: @image-url("../../resources/icons/device/hard_drive.svg");
    out property <image> no-encryption: @image-url("../../resources/icons/device/no_encryption.svg");

    // Activity types
    out property <image> settings: @image-url("../../resources/icons/action/settings.svg");
    out property <image> troubleshoot: @image-url("../../resources/icons/action/troubleshoot.svg");
    // Configure activities
    out property <image> take-ownership: @image-url("../../resources/icons/action/rocket_launch.svg");
    out property <image> activate-locking: @image-url("../../resources/icons/device/lock.svg");
    out property <image> change-password: self.password;
    out property <image> edit-ranges: @image-url("../../resources/icons/device/segment.svg");
    out property <image> edit-users: @image-url("../../resources/icons/action/person_edit.svg");
    out property <image> edit-permissions: @image-url("../../resources/icons/action/passkey.svg");
    out property <image> shadow-mbr: @image-url("../../resources/icons/action/tonality.svg");
    out property <image> revert-device: @image-url("../../resources/icons/action/lock_reset.svg");
    // Troubleshoot activities
    out property <image> com-id-status: @image-url("../../resources/icons/action/query_stats.svg");
    out property <image> stack-reset: @image-url("../../resources/icons/action/reset_wrench.svg");

    // Shapes
    out property <image> arrow-left: @image-url("../../resources/icons/shape/arrow_back_ios.svg");
    out property <image> chevron-arrow-up: @image-url("../../resources/icons/shape/chevron_up.svg");
    out property <image> chevron-arrow-down: @image-url("../../resources/icons/shape/chevron_down.svg");
    out property <image> chevron-arrow-right: @image-url("../../resources/icons/shape/chevron_right.svg");

    // Actions
    out property <image> content-copy: @image-url("../../resources/icons/action/content_copy.svg");
    out property <image> delete-forever: @image-url("../../resources/icons/action/ink_eraser.svg");
    out property <image> error: @image-url("../../resources/icons/error/error.svg");
    out property <image> warning: @image-url("../../resources/icons/error/warning.svg");
    out property <image> password: @image-url("../../resources/icons/action/pin.svg");
    out property <image> upload: @image-url("../../resources/icons/action/upload_file.svg");
    out property <image> file-open: @image-url("../../resources/icons/action/file_open.svg");
    out property <image> close: @image-url("../../resources/icons/action/close.svg");
    out property <image> cancel: @image-url("../../resources/icons/action/cancel.svg");
    out property <image> dark-mode: @image-url("../../resources/icons/action/dark_mode.svg");
    out property <image> light-mode: @image-url("../../resources/icons/action/light_mode.svg");
    out property <image> contrast: @image-url("../../resources/icons/action/contrast.svg");
}

export global IconColors {
    out property <color> take-ownership: PaletteExtra.make-accented(#00da36, Palette.control-foreground, Palette.control-background);
    out property <color> activate-locking: PaletteExtra.make-accented(#ffd92f, Palette.control-foreground, Palette.control-background);
    out property <color> change-password: PaletteExtra.make-accented(#017715, Palette.control-foreground, Palette.control-background);
    out property <color> edit-ranges: PaletteExtra.make-accented(#9900ff, Palette.control-foreground, Palette.control-background);
    out property <color> edit-users: PaletteExtra.make-accented(#006eff, Palette.control-foreground, Palette.control-background);
    out property <color> edit-permissions: PaletteExtra.make-accented(#ff9900, Palette.control-foreground, Palette.control-background);
    out property <color> shadow-mbr: PaletteExtra.make-accented(#96fcff, Palette.control-foreground, Palette.control-background);
    out property <color> revert-device: PaletteExtra.error-foreground;
    out property <color> query-status: PaletteExtra.make-accented(#ff46ff, Palette.control-foreground, Palette.control-background);
    out property <color> stack-reset: PaletteExtra.make-accented(#00a2ff, Palette.control-foreground, Palette.control-background);
}
