//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

export global Logo {
    out property <image> png: @image-url("../../resources/logo/logo.png");
    out property <image> svg: @image-url("../../resources/logo/logo.svg");
}
