[package]
name = "sed-manager-unlock"
version = "0.1.0"
edition = "2021"

[dependencies]
sed-manager = { path = "../sed_manager" }

[dependencies.tokio]
version = "1.41.0"
default-features = false
features = ["rt"]
