//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { ExtendedStatus, Status } from "../data/status.slint";
import { ConfigView } from "config_view.slint";
import { LoginView } from "login_view.slint";
import { Table, Cell } from "../widgets/table.slint";
import { LineEdit, CheckBox, Button, ComboBox, Switch } from "std-widgets.slint";
import { Icons } from "../icons.slint";
import { PaletteExtra, Island } from "../widgets/visual.slint";
import { ToastMessage } from "../widgets/toast_message.slint";
import { StatusOverlay } from "../widgets/status-overlay.slint";
import { PrototypePopup } from "../widgets/prototype_popup.slint";
import { RepeatedPasswordEdit } from "../widgets/password.slint";
import { PermissionEditorState, PermissionMatrix, PermissionList } from "../state.slint";
import { StatusIndicator } from "../widgets/progress.slint";
import { RangeAccess } from "../data/range_access.slint";

global RangeTableDesc {
    out property <[string]> column-names: ["Read unlock", "Write unlock"];
    out property <[length]> column-widths: [80px, 80px];
    out property <[float]> column-stretches: [0.2, 0.2];
    out property <length> row-height: 28px;
}

component MBRPermissionView {
    in property <bool> unshadow-mbr;
    in property <ExtendedStatus> status;
    private property <bool> enabled: status.status != Status.loading;
    callback set-mbr-permission(permitted: bool);
    changed unshadow-mbr => {
        unshadow-disp.checked = unshadow-mbr;
    }
    changed status => {
        if status.status != Status.loading {
            unshadow-disp.checked = unshadow-mbr;
        }
        if status.status == Status.error {
            ToastMessage.show("Could not update shadowing permission: " + status.message, PaletteExtra.error-foreground);
        }
    }
    HorizontalLayout {
        alignment: stretch;
        Island {
            horizontal-stretch: 0;
            background: PaletteExtra.accented-control-background;
            border-top-right-radius: 0px;
            border-bottom-right-radius: 0px;
            HorizontalLayout {
                padding: 8px;
                Text {
                    text: "Shadow MBR";
                    vertical-alignment: center;
                }
            }
        }

        Island {
            horizontal-stretch: 1;
            background: #00000000;
            border-color: PaletteExtra.accented-control-background;
            border-top-left-radius: 0px;
            border-bottom-left-radius: 0px;
            border-width: 2px;
            HorizontalLayout {
                padding: 8px;
                padding-left: 16px;
                unshadow-disp := CheckBox {
                    text: "Unshadow";
                    checked: unshadow-mbr;
                    enabled: enabled;
                    toggled => {
                        set-mbr-permission(self.checked);
                    }
                }
            }
        }
    }
}

component RangePermissionRow {
    in property <[length]> column-widths: RangeTableDesc.column-widths;
    in property <[float]> column-stretches: RangeTableDesc.column-stretches;
    in property <length> row-height: RangeTableDesc.row-height;
    in property <int> range-idx;
    in property <string> name;
    in property <bool> read-unlock;
    in property <bool> write-unlock;
    in property <ExtendedStatus> status;
    private property <bool> enabled: status.status != Status.loading;
    callback set-read-permission(permitted: bool);
    callback set-write-permission(permitted: bool);
    changed read-unlock => {
        read-unlock-disp.checked = read-unlock;
    }
    changed write-unlock => {
        write-unlock-disp.checked = write-unlock;
    }
    changed status => {
        if status.status != Status.loading {
            read-unlock-disp.checked = read-unlock;
            write-unlock-disp.checked = write-unlock;
        }
        if status.status == Status.error {
            ToastMessage.show("Could not modify " + name + ": " + status.message, PaletteExtra.error-foreground);
        }
    }
    HorizontalLayout {
        Cell {
            min-width: root.column-widths[0];
            horizontal-stretch: root.column-stretches[0];
            height: row-height;
            row-idx: range-idx;
            column-idx: 0;
            read-unlock-disp := CheckBox {
                checked: read-unlock;
                enabled: enabled;
                toggled => {
                    set-read-permission(self.checked);
                }
            }
        }

        Cell {
            min-width: root.column-widths[1];
            horizontal-stretch: root.column-stretches[1];
            height: row-height;
            row-idx: range-idx;
            column-idx: 1;
            write-unlock-disp := CheckBox {
                checked: write-unlock;
                enabled: enabled;
                toggled => {
                    set-write-permission(self.checked)
                }
            }
        }
    }
}

component RangePermissionTable {
    in property <[string]> names;
    in property <[bool]> read-unlock;
    in property <[bool]> write-unlock;
    in property <[ExtendedStatus]> statuses;
    callback set-read-permission(range-idx: int, permitted: bool);
    callback set-write-permission(range-idx: int, permitted: bool);
    table := Table {
        preferred-width: 100%;
        preferred-height: 100%;
        column-names: RangeTableDesc.column-names;
        column-widths: RangeTableDesc.column-widths;
        column-stretches: RangeTableDesc.column-stretches;
        row-names: names;
        row-heights: [RangeTableDesc.row-height];
        VerticalLayout {
            for row[range-idx] in root.names: RangePermissionRow {
                name: root.names[range-idx];
                read-unlock: read-unlock[range-idx];
                write-unlock: write-unlock[range-idx];
                status: statuses[range-idx];
                column-widths: table.column-widths;
                column-stretches: table.column-stretches;
                range-idx: range-idx;
                row-height: table.row-heights[0];
                set-read-permission(permitted) => {
                    set-read-permission(range-idx, permitted);
                }
                set-write-permission(permitted) => {
                    set-write-permission(range-idx, permitted);
                }
            }
        }
    }
}

export component PermissionEditor inherits ConfigView {
    config-name: "Edit permissions";
    config-icon: Icons.permissions;
    in property <ExtendedStatus> login-status: PermissionEditorState.login-statuses[root.device-idx];
    in property <PermissionMatrix> matrix: PermissionEditorState.matrices[root.device-idx];
    in-out property <bool> authenticated: false;
    private property <int> selected-user-idx: 0;
    private property <PermissionList> selected-user-plist: matrix.permission-lists[selected-user-idx];
    private property <ExtendedStatus> selected-user-status: matrix.user-statuses[selected-user-idx];
    changed matrix => {
        initiate-fetch(selected-user-idx)
    }
    changed selected-user-idx => {
        initiate-fetch(selected-user-idx)
    }
    function initiate-fetch(user-idx: int) {
        if selected-user-status.status != Status.success {
            PermissionEditorState.fetch(root.device-idx, user-idx);
        }
    }
    VerticalLayout {
        if !authenticated: LoginView {
            extended-status: login-status;
            user-name: "Admin1";
            login-button-text: "Edit permissions";
            back => {
                root.back();
            }
            login(password) => {
                PermissionEditorState.login(root.device-idx, password);
            }
            success => {
                authenticated = true;
                PermissionEditorState.list(root.device-idx);
            }
        }
        if authenticated: VerticalLayout {
            spacing: 16px;
            HorizontalLayout {
                alignment: start;
                ComboBox {
                    current-index <=> selected-user-idx;
                    model: matrix.user-names;
                    preferred-width: Math.max(self.min-width, 240px);
                }
            }

            if matrix.mbr-supported: MBRPermissionView {
                unshadow-mbr: selected-user-plist.unshadow-mbr;
                status: selected-user-plist.unshadow-mbr-status;
                set-mbr-permission(permitted) => {
                    PermissionEditorState.set-mbr-permission(root.device-idx, selected-user-idx, permitted);
                }
            }
            RangePermissionTable {
                names: matrix.range-names;
                read-unlock: selected-user-plist.read-unlock;
                write-unlock: selected-user-plist.write-unlock;
                statuses: selected-user-plist.range-statuses;
                set-read-permission(range-idx, permitted) => {
                    PermissionEditorState.set-read-permission(root.device-idx, selected-user-idx, range-idx, permitted);
                }
                set-write-permission(range-idx, permitted) => {
                    PermissionEditorState.set-write-permission(root.device-idx, selected-user-idx, range-idx, permitted);
                }
            }
        }
        if authenticated && login-status.status != Status.success: StatusOverlay {
            status: login-status;
        }
        if authenticated && selected-user-status.status != Status.success && login-status.status == Status.success: StatusOverlay {
            status: selected-user-status;
        }
    }
}

global ExampleMatrix {
    out property <PermissionMatrix> matrix: {
        mbr-supported: true,
        user-names: ["User1", "User2"],
        range-names: ["GlobalRange", "Range1", "Range2"],
        user-statuses: [{ status: Status.success }, { status: Status.error, message: "fetch failed" }],
        permission-lists: [
            {
                unshadow-mbr: false,
                unshadow-mbr-status: { status: Status.loading },
                read-unlock: [true, false, false],
                write-unlock: [true, false, false],
                range-statuses: [{ status: Status.success }, { status: Status.success }, { status: Status.loading }]
            },
            {
                unshadow-mbr: true,
                unshadow-mbr-status: { status: Status.success },
                read-unlock: [true, true, false],
                write-unlock: [false, true, false],
                range-statuses: [{ status: Status.success }, { status: Status.loading }, { status: Status.success }]
            }
        ],
    };
}

export component LivePreviewTest_RangeTable inherits RangePermissionTable { }

export component LivePreviewTest_ListError inherits PermissionEditor {
    device-name: "Foo Device";
    login-status: { status: Status.error, message: "sample error" };
    authenticated: true;
    matrix: ExampleMatrix.matrix;
}

export component LivePreviewTest_ListLoading inherits PermissionEditor {
    device-name: "Foo Device";
    login-status: { status: Status.loading };
    authenticated: true;
    matrix: ExampleMatrix.matrix;
}

export component LivePreviewTest_Auth inherits PermissionEditor {
    device-name: "Foo Device";
    login-status: { status: Status.success };
    authenticated: true;
    matrix: ExampleMatrix.matrix;
}

export component LivePreviewTest inherits PermissionEditor {
    device-name: "Foo Device";
    login-status: { status: Status.loading };
    matrix: ExampleMatrix.matrix;
}
