//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { PaletteExtra } from "palette_extra.slint";
import { Palette } from "std-widgets.slint";

export component HorizontalSeparator inherits Rectangle {
    preferred-width: 100%;
    height: 1px;
    background: PaletteExtra.separator;
}

export component VerticalSeparator inherits Rectangle {
    width: 1px;
    preferred-height: 100%;
    background: PaletteExtra.separator;
}

export component Island inherits Rectangle {
    background: Palette.control-background;
    border-radius: 8px;

    // Get padding from sides that give `distance` at the rounded corners.
    public pure function corner-padding(distance: length) -> length {
        (self.border-radius * (Math.sqrt(2.0) - 1.0) + distance) / Math.sqrt(2.0);
    }
}
