import { LineEdit, Button } from "std-widgets.slint";
import { CommandStatus } from "../../data/lib.slint";

export component ActivateLockingView {
    in property <CommandStatus> command-status;

    callback activate-locking();

    VerticalLayout {
        spacing: 0.5rem;
        alignment: start;

        Text {
            text: "Owner (SID) password:";
        }

        LineEdit { }

        Button {
            text: "Activate locking";
            primary: true;
            clicked => {
                activate-locking()
            }
            enabled: !command-status.session-busy && !command-status.tper-busy;
        }
    }
}
