import { ComboBox, LineEdit, Button } from "std-widgets.slint";
import { PasswordForm } from "../password_form.slint";
import { HorizontalSeparator } from "../../widgets/lib.slint";
import { CommandStatus } from "../../data/lib.slint";

export component ChangePasswordView {
    in property <CommandStatus> command-status;

    callback change-password();

    VerticalLayout {
        alignment: start;
        spacing: 0.5rem;

        Text {
            text: "Security provider:";
        }

        ComboBox { }

        Text {
            text: "Authority:";
        }

        ComboBox { }

        Text {
            text: "Current password:";
        }

        LineEdit {
            input-type: InputType.password;
        }

        Rectangle {
            height: 1.2rem;
        }

        password-form := PasswordForm { }

        Button {
            text: "Change password";
            primary: true;
            clicked => {
                change-password()
            }
            enabled: password-form.matches && !command-status.session-busy && !command-status.tper-busy;
        }
    }
}
