import { ComboBox, LineEdit, Button } from "std-widgets.slint";
import { PasswordForm } from "../password_form.slint";
import { HorizontalSeparator } from "../../widgets/lib.slint";
import { CommandStatus, SecurityProvider, Uid } from "../../data/lib.slint";

export component ChangePasswordView {
    in property <CommandStatus> command-status;
    in property <SecurityProvider> admin-sp;
    in property <SecurityProvider> locking-sp;

    callback change-password(sp: Uid, authority: Uid, current-password: string, new-password: string);

    VerticalLayout {
        alignment: start;
        spacing: 0.5rem;

        Text {
            text: "Security provider:";
        }

        sp-selector := ComboBox {
            model: [
                admin-sp.name,
                locking-sp.name,
            ];
        }

        Text {
            text: "Authority:";
        }

        authority-selector := ComboBox {
            model: [
                admin-sp.individual-user-names,
                locking-sp.individual-user-names,
            ][sp-selector.current-index];
        }

        Text {
            text: "Current password:";
        }

        current-password := LineEdit {
            input-type: InputType.password;
        }

        Rectangle {
            height: 1.2rem;
        }

        password-form := PasswordForm { }

        Button {
            text: "Change password";
            primary: true;
            clicked => {
                change-password(
                    [
                    admin-sp.uid,
                    locking-sp.uid,
                ][sp-selector.current-index],
                    [
                    admin-sp.individual-user-uids,
                    locking-sp.individual-user-uids,
                ][sp-selector.current-index][authority-selector.current-index],
                    current-password.text,
                    password-form.password,
                )
            }
            enabled: password-form.matches && !command-status.session-busy && !command-status.tper-busy;
        }
    }
}
