import {
    ToastCard,
    ToastLevel,
    PaletteExtra,
} from "../../widgets/lib.slint";
import {
    CommandStatus,
    SecurityProvider,
    LockingRange,
} from "../../data/lib.slint";
import {
    TabWidget,
    ScrollView,
    LineEdit,
    CheckBox,
    Palette,
    Button,
} from "std-widgets.slint";
import { Sector, SectorUtil } from "../../data/sector.slint";
import { LockingRangesTab } from "locking/locking_ranges.slint";
import { AuthoritiesTab } from "locking/authorities.slint";
import { ShadowMbrTab } from "locking/shadow_mbr.slint";


export component ConfigureLockingView {
    in property <CommandStatus> command-status;
    in-out property <SecurityProvider> locking-sp;

    TabWidget {
        Tab {
            title: "Locking ranges";

            VerticalLayout {
                alignment: start;
                padding-top: 1.2rem;

                LockingRangesTab {
                    locking-ranges <=> locking-sp.locking-ranges;
                    command-status: command-status;
                }
            }
        }

        Tab {
            title: "Authorities";

            VerticalLayout {
                alignment: start;
                padding-top: 1.2rem;

                AuthoritiesTab {
                    authorities <=> locking-sp.authorities;
                    command-status: command-status;
                    mbr: locking-sp.mbr;
                }
            }
        }

        Tab {
            title: "Shadow MBR";

            VerticalLayout {
                alignment: start;
                padding-top: 1.2rem;

                ShadowMbrTab {
                    command-status: command-status;
                    mbr <=> locking-sp.mbr;
                }
            }
        }
    }
}
