import { LineEdit, GroupBox, Button, Palette } from "std-widgets.slint";
import { Island, PaletteExtra } from "../widgets/visual.slint";
import { ContentStatus } from "../data/content_status.slint";
import { ActionView } from "device_description_view/action_view.slint";
import { DiscoveryView } from "device_description_view/discovery_view.slint";
import { IdentityView } from "device_description_view/identity_view.slint";
import { DeviceDescription, ExampleData } from "../data/device_description.slint";

export component DeviceDescriptionView {
    in property <DeviceDescription> description;
    callback take-ownership <=> action-view.take-ownership;
    callback activate-locking <=> action-view.activate-locking;
    callback configure-ranges <=> action-view.configure-ranges;
    callback revert <=> action-view.revert;
    callback update-com-id-status <=> action-view.update-com-id-status;
    callback stack-reset <=> action-view.stack-reset;
    VerticalLayout {
        spacing: 20px;
        IdentityView {
            identity: description.identity;
            security-subsystem-classes: description.discovery.security-subsystem-classes;
            vertical-stretch: 0.0;
        }

        HorizontalLayout {
            spacing: 20px;
            alignment: stretch;
            vertical-stretch: 1.0;
            DiscoveryView {
                horizontal-stretch: 1.0;
                status: description.discovery-status;
                error-message: description.discovery-error-message;
                discovery: description.discovery;
            }

            action-view := ActionView {
                horizontal-stretch: 0.0;
                security-providers: description.discovery.security-providers;
            }
        }
    }
}

export component LivePreviewTest_Page inherits DeviceDescriptionView {
    description: ExampleData.description;
}
