import { Button, VerticalBox, Palette, HorizontalBox } from "std-widgets.slint";
import { Interface, InterfaceProperties } from "interface.slint";
import { SSC, SSCProperties } from "ssc.slint";

export global CardLayoutSize {
    out property <length> width: 240px;
    out property <length> height: 104px;
    out property <length> spacing: 16px;
}

export component DeviceCard inherits Rectangle {
    width: CardLayoutSize.width;
    height: CardLayoutSize.height;
    background: gradient;
    border-radius: 8px;
    drop-shadow-offset-x: 8px;
    drop-shadow-offset-y: 8px;
    drop-shadow-color: self.tint.mix(#000000, 0.2).with-alpha(0.6);
    drop-shadow-blur: 8px;
    border-width: 1px;
    border-color: self.highlight;
    in property <string> name;
    in property <SSC> ssc;
    in property <Interface> interface;
    in property <string> serial;
    in property <string> firmware;
    property <color> tint: SSCProperties.color(self.ssc).mix(Palette.background, 0.5);
    property <color> highlight: self.tint.mix(Palette.foreground, 0.5);
    property <color> base: self.get_background_color(touch-area.has-hover, self.tint, self.highlight);
    property <brush> gradient: @linear-gradient(40deg, self.tint.darker(0.25) 0%, self.base 40%, self.base.brighter(0.05) 70%, self.tint 100%);
    pure function get_background_color(is-highlighted: bool, normal: color, highlight: color) -> brush {
        if !is-highlighted {
            normal
        } else {
            normal.mix(highlight, 0.65)
        }
    }
    touch-area := TouchArea {
        width: parent.width;
        height: parent.height;
        enabled: parent.ssc != SSC.unsupported;
    }

    VerticalLayout {
        alignment: start;
        padding-top: 6px;
        padding-bottom: 6px;
        padding-left: 12px;
        padding-right: 12px;
        Text {
            horizontal-alignment: center;
            text: name;
            font-size: 14px;
            font-weight: 800;
        }

        HorizontalBox {
            height: 6px;
        }

        Rectangle {
            height: 1px;
            background: @linear-gradient(90deg, tint 0%, highlight 25%, highlight 75%, tint 100%);
        }

        HorizontalLayout {
            alignment: space-between;
            padding-top: 4px;
            padding-bottom: 6px;
            Text {
                text: SSCProperties.name(ssc);
                font-weight: 800;
            }

            Text {
                text: InterfaceProperties.name(interface);
                font-weight: 800;
            }
        }

        Rectangle {
            height: 1px;
            background: @linear-gradient(90deg, tint 0%, highlight 25%, highlight 75%, tint 100%);
        }

        HorizontalLayout {
            alignment: space-between;
            padding-top: 2px;
            Text {
                text: "Serial:";
            }

            Text {
                text: serial;
            }
        }

        HorizontalLayout {
            alignment: space-between;
            Text {
                text: "Firmare:";
            }

            Text {
                text: firmware;
            }
        }
    }
}
