
export enum SSC {
    enterprise,
    opal-v1,
    opal-v2,
    opalite,
    pyrite-v1,
    pyrite-v2,
    ruby,
    key-per-io,
    unsupported,
}


export global SSCProperties {
    public pure function name(ssc: SSC) -> string {
        if ssc == SSC.enterprise {
            "TCG Enterprise"
        } else if ssc == SSC.key_per_io {
            "TCG Key Per I/O"
        } else if ssc == SSC.opalite {
            "TCG Opalite"
        } else if ssc == SSC.opal-v1 {
            "TCG Opal 1.0"
        } else if ssc == SSC.opal-v2 {
            "TCG Opal 2.0"
        } else if ssc == SSC.pyrite-v1 {
            "TCG Pyrite 1.0"
        } else if ssc == SSC.pyrite-v2 {
            "TCG Pyrite 2.0"
        } else if ssc == SSC.ruby {
            "TCG Ruby"
        } else {
            "Unsupported"
        }
    }
    public pure function color(ssc: SSC) -> color {
        if ssc == SSC.enterprise {
            #00a531
        } else if ssc == SSC.key-per-io {
            #995642
        } else if ssc == SSC.opalite {
            #0073a0
        } else if ssc == SSC.opal-v1 {
            #0d80dd
        } else if ssc == SSC.opal-v2 {
            #0d80dd
        } else if ssc == SSC.pyrite-v1 {
            #c8ca37
        } else if ssc == SSC.pyrite-v2 {
            #c8ca37
        } else if ssc == SSC.ruby {
            #8a0007
        } else {
            #808080
        }
    }
}