[package]
name = "sed-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sed_manager_macros = { path = "../sed_manager_macros" }

[dependencies.bitvec]
version = "1"
default-features = false
features = ["alloc"]
