[package]
name = "sed-manager-macros"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
proc-macro2 = "1.0.89"

[dependencies.syn]
version = "2.0.83"
features = ["parsing", "full"]