import { ConfigView } from "config_view.slint";
import { LineEdit, Button, CheckBox, ScrollView, Palette } from "std-widgets.slint";
import { ExtendedStatus, Status } from "../data/status.slint";
import { LockingRange } from "../data/locking_range.slint";
import { PaletteExtra, VerticalSeparator, Island } from "../widgets/visual.slint";
import { NavigationButton, NavigationDirection } from "../widgets/navigation_button.slint";
import { ResultPopup } from "../widgets/result_popup.slint";
import { Table, Cell } from "../widgets/table.slint";
import { Types } from "../data/types.slint";
import { WarningPopup } from "../widgets/warning_popup.slint";
import { StatusIndicator } from "../widgets/progress.slint";
import { ToastMessage } from "../widgets/toast_message.slint";
import { Icons } from "../icons.slint";

component LoginForm {
    out property <string> admin1_password;
    in property <bool> enabled;
    callback executed();
    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            vertical-stretch: 1.0;
            padding: 8px;
            spacing: 6px;
            alignment: center;
            Text {
                text: "Enter Admin1 password:";
            }

            password := LineEdit {
                input-type: InputType.password;
                text <=> root.admin1_password;
            }

            Button {
                primary: true;
                text: "Configure locking ranges";
                clicked => {
                    executed();
                }
            }
        }
    }
}

component LoginView {
    in property <ExtendedStatus> extended-status;
    out property <bool> back-enabled: extended-status.status != Status.loading;
    callback back();
    callback login(admin1_password: string);
    Rectangle {
        result-popup := ResultPopup {
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
            finish-enabled: root.back-enabled;
            retry-enabled: root.back-enabled;
            finish-text: "Back";
            status: extended-status.status;
            hide-on-success: true;
            message: {
                if extended-status.status == Status.success {
                    "Session started!"
                } else if extended-status.status == Status.error {
                    "Failed to start session:\n" + extended-status.message
                } else {
                    "Starting Admin1 session..."
                }
            }
            finished => {
                self.close();
                root.back();
            }
            retried => {
                self.close();
            }
        }
    }

    HorizontalLayout {
        alignment: center;
        vertical-stretch: 1.0;
        form := LoginForm {
            enabled: root.back-enabled;
            executed => {
                result-popup.show();
                login(self.admin1_password);
            }
        }
    }
}

global TableDesc {
    out property <[string]> column-names: [
        "Start\n(LBA)",
        "Length\n(LBA)",
        "End\n(LBA)",
        "Read lock\n enabled",
        "Write lock\n enabled",
        "Read locked",
        "Write locked",
        "Erase",
    ];
    out property <[length]> column-widths: [
        100px,
        100px,
        100px,
        80px,
        80px,
        80px,
        80px,
        60px,
    ];
    out property <length> row-height: 32px;
}

component EraseWarningMessage {
    in property <string> range-name;
    VerticalLayout {
        alignment: center;
        spacing: 8px;
        Text {
            text: "Erase " + range-name + "?";
            font-weight: 600;
        }

        Text {
            text: "The data is erased cryptographically, and there is no way to recover it.";
        }
    }
}

component CheckLockingRange {
    in property <int> alignment: 1;
    in-out property <int> start-lba;
    in-out property <int> length-lba;
    in-out property <int> end-lba;
    in-out property <bool> read-lock-enabled;
    in-out property <bool> write-lock-enabled;
    in-out property <bool> read-locked;
    in-out property <bool> write-locked;
    pure function align(value: int) -> int {
        Math.floor(value / alignment) * alignment
    }
    public function set-start(new-start: int) {
        start-lba = align(Math.max(0, new-start));
        end-lba = Math.max(start-lba, end-lba);
        length-lba = end-lba - start-lba;
    }
    public function set-end(new-end: int) {
        end-lba = align(Math.max(0, new-end));
        start-lba = Math.min(start-lba, end-lba);
        length-lba = end-lba - start-lba;
    }
    public function set-length(new-length: int) {
        end-lba = start-lba + align(Math.max(0, new-length));
        length-lba = end-lba - start-lba;
    }
    public function set-range(properties: LockingRange) {
        start-lba = properties.start-lba;
        length-lba = properties.end-lba - properties.start-lba;
        end-lba = properties.end-lba;
        read-lock-enabled = properties.read-lock-enabled;
        write-lock-enabled = properties.write-lock-enabled;
        read-locked = properties.read-locked;
        write-locked = properties.write-locked;
    }
    public function get-range() -> LockingRange {
        {
            start-lba: start-lba,
            end-lba: end-lba,
            read-lock-enabled: read-lock-enabled,
            write-lock-enabled: write-lock-enabled,
            read-locked: read-locked,
            write-locked: write-locked,
        }
    }
}

component Range {
    in property <[length]> column-widths: TableDesc.column-widths;
    in property <length> row-height: TableDesc.row-height;
    in property <int> range-idx;
    in-out property <LockingRange> range;
    in property <Status> status;
    private property <bool> enabled: status != Status.loading;
    callback set-locking-range(value: LockingRange);
    callback erase-locking-range();
    changed range => {
        checked-range.set-range(range);
    }
    changed status => {
        if status == Status.error {
            checked-range.set-range(range);
        }
    }
    checked-range := CheckLockingRange {
        start-lba: range.start-lba;
        length-lba: range.end-lba - range.start-lba;
        end-lba: range.end-lba;
        read-lock-enabled: range.read-lock-enabled;
        write-lock-enabled: range.write-lock-enabled;
        read-locked: range.read-locked;
        write-locked: range.write-locked;
        changed start-lba => {
            start-lba.text = self.start-lba;
        }
        changed length-lba => {
            length-lba.text = self.length-lba;
        }
        changed end-lba => {
            end-lba.text = self.end-lba;
        }
    }

    HorizontalLayout {
        Cell {
            width: root.column-widths[0];
            height: row-height;
            row-idx: range-idx;
            column-idx: 0;
            start-lba := LineEdit {
                width: parent.width;
                input-type: number;
                horizontal-alignment: right;
                text: checked-range.start-lba;
                enabled: enabled;
                accepted(text) => {
                    self.clear-focus();
                    checked-range.set-start(Types.str-to-int(text));
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[1];
            height: row-height;
            row-idx: range-idx;
            column-idx: 1;
            length-lba := LineEdit {
                width: parent.width;
                input-type: number;
                horizontal-alignment: right;
                text: checked-range.length-lba;
                enabled: enabled;
                accepted(text) => {
                    self.clear-focus();
                    checked-range.set-length(Types.str-to-int(text));
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[2];
            height: row-height;
            row-idx: range-idx;
            column-idx: 2;
            end-lba := LineEdit {
                width: parent.width;
                input-type: number;
                horizontal-alignment: right;
                text: checked-range.end-lba;
                enabled: enabled;
                accepted(text) => {
                    self.clear-focus();
                    checked-range.set-end(Types.str-to-int(text));
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[3];
            height: row-height;
            row-idx: range-idx;
            column-idx: 3;
            rd-lock-en := CheckBox {
                checked <=> checked-range.read-lock-enabled;
                enabled: enabled;
                toggled => {
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[4];
            height: row-height;
            row-idx: range-idx;
            column-idx: 4;
            wr-lock-en := CheckBox {
                checked <=> checked-range.write-lock-enabled;
                enabled: enabled;
                toggled => {
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[5];
            height: row-height;
            row-idx: range-idx;
            column-idx: 5;
            rd-locked := CheckBox {
                checked <=> checked-range.read-locked;
                enabled: enabled;
                toggled => {
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[6];
            height: row-height;
            row-idx: range-idx;
            column-idx: 6;
            wr-locked := CheckBox {
                checked <=> checked-range.write-locked;
                enabled: enabled;
                toggled => {
                    set-locking-range(checked-range.get-range());
                }
            }
        }

        Cell {
            width: root.column-widths[7];
            height: row-height;
            row-idx: range-idx;
            column-idx: 7;
            Button {
                height: 100%;
                width: 100%;
                icon: Icons.delete-forever;
                enabled: enabled;
                clicked => {
                    erase-locking-range();
                }
            }
        }
    }
}

component RangeTable {
    in property <[string]> names;
    in property <[LockingRange]> ranges;
    in property <[ExtendedStatus]> statuses;
    callback set-locking-range(range-idx: int, value: LockingRange);
    callback erase-locking-range(range-idx: int);
    private property <int> warned-range-idx;
    erase-warning := WarningPopup {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        continue-text: "Erase";
        EraseWarningMessage {
            range-name: names[warned-range-idx];
        }

        continued => {
            self.close();
            erase-locking-range(warned-range-idx);
        }
        cancelled => {
            self.close();
        }
    }

    HorizontalLayout {
        alignment: stretch;
        VerticalLayout {
            alignment: stretch;
            padding-top: 16px;
            table := Table {
                column-names: TableDesc.column-names;
                column-widths: TableDesc.column-widths;
                row-names: names;
                row-heights: [TableDesc.row-height];
                VerticalLayout {
                    for row[range-idx] in root.names: Range {
                        range: ranges[range-idx];
                        status: statuses[range-idx].status;
                        column-widths: table.column-widths;
                        range-idx: range-idx;
                        row-height: table.row-heights[0];
                        set-locking-range(value) => {
                            set-locking-range(range-idx, value);
                        }
                        erase-locking-range() => {
                            warned-range-idx = range-idx;
                            erase-warning.show();
                        }
                        changed status => {
                            if self.status == Status.error {
                                ToastMessage.show("Could not modify " + names[range-idx] + ": " + statuses[range-idx].message, PaletteExtra.error-foreground);
                                self.range = ranges[range-idx];
                            }
                        }
                    }
                }
            }
        }
    }
}

export component LockingRanges inherits ConfigView {
    config-name: "Locking ranges";
    config-icon: Icons.locking-ranges;
    in property <ExtendedStatus> login-status;
    in property <[string]> names;
    in property <[LockingRange]> ranges;
    in property <[ExtendedStatus]> statuses;
    private property <bool> authenticated: false;
    callback login-locking-ranges(password: string);
    callback list-locking-ranges();
    callback set-locking-range(range-idx: int, value: LockingRange);
    callback erase-locking-range(range-idx: int);
    changed login-status => {
        if login-status.status == Status.success {
            authenticated = true;
            list-locking-ranges();
        }
    }
    form := VerticalLayout {
        if !authenticated: LoginView {
            extended-status: login-status;
            back => {
                root.back();
            }
            login(password) => {
                login-locking-ranges(password);
            }
        }
        if authenticated: RangeTable {
            names: names;
            ranges: ranges;
            statuses: statuses;
            set-locking-range(range-idx, value) => {
                set-locking-range(range-idx, value);
            }
            erase-locking-range(range-idx) => {
                erase-locking-range(range-idx);
            }
        }
    }
}

global ExampleRanges {
    out property <[string]> names: [
        "GlobalRange",
        "Range1",
        "Range2",
    ];
    out property <[LockingRange]> ranges: [
        {
            start-lba: 0,
            end-lba: 0,
            read-lock-enabled: false,
            write-lock-enabled: false,
            read-locked: false,
            write-locked: false,
        },
        {
            start-lba: 1000,
            end-lba: 2000,
            read-lock-enabled: true,
            write-lock-enabled: true,
            read-locked: false,
            write-locked: false,
        },
        {
            start-lba: 0,
            end-lba: 0,
            read-lock-enabled: false,
            write-lock-enabled: false,
            read-locked: false,
            write-locked: false,
        },
    ];
    out property <[ExtendedStatus]> statuses: [
        { status: Status.success },
        { status: Status.loading },
        { status: Status.error, message: "sample error" },
    ];
}

export component LivePreviewTest_RangeTable inherits RangeTable {
    names: ExampleRanges.names;
    ranges: ExampleRanges.ranges;
    statuses: ExampleRanges.statuses;
}

export component LivePreviewTest inherits LockingRanges {
    device-name: "Foo Device";
    names: ExampleRanges.names;
    ranges: ExampleRanges.ranges;
    login-status: { status: Status.success };
    timer := Timer {
        interval: 1s;
        running: false;
        triggered => {
            self.running = false;
            root.login-status.status = Status.success;
        }
    }
}
