//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { LineEdit } from "std-widgets.slint";

export global Password {
    public pure function validate(password: string, repeat: string) -> string {
        if password == "1234" {
            "Cannot be the same as mine"
        } else if password != repeat {
            "Passwords do not match"
        } else {
            "";
        }
    }
}

export component RepeatedPasswordEdit {
    in property <string> prompt-text: "Enter new password:";
    in property <string> repeat-text: "Repeat passowrd:";
    in property <bool> enabled: true;
    out property <bool> accepted: reason == "";
    out property <string> reason;
    out property <string> password <=> password.text;
    VerticalLayout {
        spacing: 4px;
        Text {
            text: prompt-text;
            opacity: enabled ? 100% : 50%;
        }

        password := LineEdit {
            input-type: InputType.password;
            edited(text) => {
                reason = Password.validate(password.text, repeat.text);
            }
            enabled: enabled;
        }

        Text {
            text: repeat-text;
            opacity: enabled ? 100% : 50%;
        }

        repeat := LineEdit {
            input-type: InputType.password;
            edited(text) => {
                reason = Password.validate(password.text, repeat.text);
            }
            enabled: enabled;
        }
    }
}
