import { Palette } from "std-widgets.slint";
import { HorizontalSeparator, Island } from "visual.slint";
import { NavigationButton, NavigationDirection } from "navigation_button.slint";

export component Collapsible inherits Island {
    in property <string> text;
    in property <image> icon;
    in-out property <bool> collapsed: false;
    in property <length> header-height: 32px;
    in property <length> font-size;
    in property <color> font-color: Palette.control-foreground;
    min-height: collapsed ? header-height : layout.min-height;
    layout := VerticalLayout {
        alignment: start;
        header := NavigationButton {
            text: root.text;
            icon: root.icon;
            font-size: root.font-size;
            icon-color: font-color;
            text-color: font-color;
            height: Math.max(header-height, self.min-height);
            background: #00000000;
            navigation-direction: root.collapsed ? NavigationDirection.down : NavigationDirection.up;
            clicked => {
                root.collapsed = !root.collapsed;
            }
        }

        content := Rectangle {
            visible: !collapsed;
            @children
        }
    }
}

export component LivePreviewTest inherits Collapsible {
    text: "Title";
    VerticalLayout {
        Text {
            text: "Some text for you";
        }

        Text {
            text: "And some more";
        }
    }
}
