//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { Palette } from "std-widgets.slint";
import { PaletteExtra } from "visual.slint";

export component PrototypePopup inherits PopupWindow {
    in property <length> border-radius: 16px;
    in property <length> border-width: 0px;
    in property <color> border-color: PaletteExtra.accent.with-alpha(0.25);

    Rectangle {
        opacity: 95%;

        Rectangle {
            background: #00000000;
            border-radius: border-radius;
            x: -6px;
            y: -6px;
            width: root.width + 12px;
            height: root.height + 12px;
            drop-shadow-color: #00000060;
            drop-shadow-blur: 32px;
            drop-shadow-offset-x: 3px;
            drop-shadow-offset-y: 3px;
        }

        Rectangle {
            background: Palette.background;
            border-radius: border-radius;
        }

        Rectangle {
            background: Palette.control-background;
            border-radius: border-radius;
            border-width: border-width;
            border-color: border-color;
        }
    }

    @children
}
