//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { GroupBox, Button, Palette, ScrollView } from "std-widgets.slint";
import { Collapsible } from "../../widgets/collapsible.slint";
import { NavigationButton, NavigationDirection } from "../../widgets/navigation_button.slint";
import { HorizontalSeparator, PaletteExtra } from "../../widgets/visual.slint";
import { Activity, ActivitySupport } from "../../data/activity.slint";
import { Icons, IconColors } from "../../icons.slint";

export component ActivityLauncher {
    in property <ActivitySupport> activity-support;
    in property <[string]> security-providers;
    private property <length> button-height: 32px;
    callback select-activity(activity: Activity);
    ScrollView {
        horizontal-scrollbar-policy: always-off;
        min-width: viewport.min-width;
        min-height: 128px;
        viewport := VerticalLayout {
            alignment: start;
            spacing: 12px;
            Collapsible {
                text: "Configure";
                icon: Icons.settings;
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Take ownership";
                        icon: Icons.take-ownership;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.take-ownership;
                        enabled: activity-support.take-ownership;
                        clicked => {
                            select-activity(Activity.take-ownership);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Activate locking";
                        icon: Icons.activate-locking;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.activate-locking;
                        enabled: activity-support.activate-locking;
                        clicked => {
                            select-activity(Activity.activate-locking);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit ranges";
                        icon: Icons.edit-ranges;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.edit-ranges;
                        enabled: activity-support.range-editor;
                        clicked => {
                            select-activity(Activity.range-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit users";
                        icon: Icons.edit-users;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.edit-users;
                        enabled: activity-support.user-editor;
                        clicked => {
                            select-activity(Activity.user-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Edit permissions";
                        icon: Icons.edit-permissions;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.edit-permissions;
                        enabled: activity-support.access-control-editor;
                        clicked => {
                            select-activity(Activity.access-control-editor);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Shadow MBR";
                        icon: Icons.shadow-mbr;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.shadow-mbr;
                        enabled: activity-support.shadow-mbr;
                        clicked => {
                            select-activity(Activity.shadow-mbr);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Revert device";
                        icon: Icons.revert-device;
                        height: button-height;
                        navigation-direction: NavigationDirection.left;
                        background: #00000000;
                        icon-color: IconColors.revert-device;
                        enabled: activity-support.revert;
                        clicked => {
                            select-activity(Activity.revert);
                        }
                    }
                }
            }

            Collapsible {
                text: "Troubleshoot";
                icon: Icons.troubleshoot;
                preferred-height: self.min-height;
                font-color: PaletteExtra.accented-control-foreground;
                header-height: 42px;
                VerticalLayout {
                    alignment: start;
                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Query stack status";
                        icon: Icons.com-id-status;
                        height: button-height;
                        background: #00000000;
                        icon-color: IconColors.query-status;
                        enabled: activity-support.com-id-status;
                        clicked => {
                            select-activity(Activity.com-id-status);
                        }
                    }

                    HorizontalSeparator {
                        background: Palette.background;
                    }

                    NavigationButton {
                        text: "Reset stack";
                        icon: Icons.stack-reset;
                        height: button-height;
                        background: #00000000;
                        icon-color: IconColors.stack-reset;
                        enabled: activity-support.stack-reset;
                        clicked => {
                            select-activity(Activity.stack-reset);
                        }
                    }
                }
            }
        }
    }
}

export component LivePreviewTest inherits ActivityLauncher {
    security-providers: ["Admin", "Locking"];
}
