name: Build & test

on:
  push:
    branches: [ "master" ]
    tags:
      - v**.**
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        cargo_profile: [dev, release]
        os: [windows-latest]
        include:
          - cargo_profile: dev
            cargo_folder: debug
          - cargo_profile: release
            cargo_folder: release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --profile ${{ matrix.cargo_profile }} --verbose
    - name: Run tests
      run: cargo test --profile ${{ matrix.cargo_profile }} --verbose

    - name: "Upload binaries"
      uses: actions/upload-artifact@v4
      with:
        name: sed-manager-gui-${{ matrix.cargo_profile }}
        path: "${{ github.workspace }}/target/${{ matrix.cargo_folder }}/sed-manager-gui*"
        if-no-files-found: error