name: build_and_test

on:
  push:
    branches: [ "master" ]
    tags:
      - v**.**
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        cargo_profile: [dev, release]
        os: [windows-latest, ubuntu-latest]
        include:
          - cargo_profile: dev
            cargo_folder: debug
          - cargo_profile: release
            cargo_folder: release
          - os: windows-latest
            os_name: windows
          - os: ubuntu-latest
            os_name: linux
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libfontconfig-dev
        sudo apt install libfreetype-dev        

    - name: Build
      run: cargo build --profile ${{ matrix.cargo_profile }} --verbose

    - name: Run tests
      run: cargo test --profile ${{ matrix.cargo_profile }} --verbose

    - name: "Upload binaries"
      uses: actions/upload-artifact@v4
      with:
        name: sed-manager-${{ matrix.os_name }}-${{ matrix.cargo_profile }}
        path: |
          ${{ github.workspace }}/target/${{ matrix.cargo_folder }}/sed-manager-config*
          ${{ github.workspace }}/target/${{ matrix.cargo_folder }}/sed-manager-unlock*
          !${{ github.workspace }}/target/${{ matrix.cargo_folder }}/*.d
          !${{ github.workspace }}/target/${{ matrix.cargo_folder }}/*.pdb
        if-no-files-found: error