//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { PaletteExtra } from "palette_extra.slint";
import { Palette, Button } from "std-widgets.slint";
import { IslandButton } from "island_button.slint";

export component IconButton inherits IslandButton {
    preferred-height: 2rem;
    has-background: false;

    in property <image> icon;
    in property <string> text;
    in property <length> font-size;

    VerticalLayout {
        Image {
            source: icon;
            image-fit: contain;
            horizontal-alignment: center;
            vertical-alignment: center;
            colorize: root.foreground;
        }

        if !text.is-empty: Text {
            text: text;
            horizontal-alignment: center;
            color: root.foreground;
            font-size: font-size;
        }
    }
}
