//L-----------------------------------------------------------------------------
//L Copyright (C) Péter Kardos
//L Please refer to the full license distributed with this software.
//L-----------------------------------------------------------------------------

import { PaletteExtra } from "palette_extra.slint";

export component HorizontalSeparator inherits Rectangle {
    preferred-width: 100%;
    height: 0.1rem;
    background: PaletteExtra.separator;
}

export component VerticalSeparator inherits Rectangle {
    width: 0.1rem;
    preferred-height: 100%;
    background: PaletteExtra.separator;
}
